DROP TABLE TS001_JOB_SCH;/* 일정 */
DROP TABLE TU001_USER_I;/* 사용자_정보 */
--------------------------------------------------------------------------------
/* 사용자_정보 */
CREATE TABLE alarm.TU001_USER_I (
	DEVER_ID VARCHAR2(10) NOT NULL, /* 개발자ID */
	DEVER_PW VARCHAR2(10) NOT NULL, /* 개발자PW */
	LST_CONN_TS TIMESTAMP DEFAULT SYSTIMESTAMP, /* 최종접속일시 */
	LST_CONN_IP VARCHAR2(20), /* 최종접속IP */
	DEL_YN CHAR(1) DEFAULT 'N', /* 삭제여부 */
	FST_PC_TS TIMESTAMP DEFAULT SYSTIMESTAMP, /* 최초처리일시 */
	LUPD_CNT INTEGER DEFAULT 0 /* 최종수정수 */
);

COMMENT ON TABLE alarm.TU001_USER_I IS '사용자_정보';

COMMENT ON COLUMN alarm.TU001_USER_I.DEVER_ID IS '개발자ID';

COMMENT ON COLUMN alarm.TU001_USER_I.DEVER_PW IS '개발자PW';

COMMENT ON COLUMN alarm.TU001_USER_I.LST_CONN_TS IS '최종접속일시';

COMMENT ON COLUMN alarm.TU001_USER_I.LST_CONN_IP IS '최종접속IP';

COMMENT ON COLUMN alarm.TU001_USER_I.DEL_YN IS '삭제여부';

COMMENT ON COLUMN alarm.TU001_USER_I.FST_PC_TS IS '최초처리일시';

COMMENT ON COLUMN alarm.TU001_USER_I.LUPD_CNT IS '최종수정수';

CREATE UNIQUE INDEX alarm.PK_TU001_USER_I
	ON alarm.TU001_USER_I (
		DEVER_ID ASC
	);

ALTER TABLE alarm.TU001_USER_I
	ADD
		CONSTRAINT PK_TU001_USER_I
		PRIMARY KEY (
			DEVER_ID
		);

/* 일정 */
CREATE TABLE alarm.TS001_JOB_SCH (
	DEVER_ID VARCHAR2(10) NOT NULL, /* 개발자ID */
	CUST_ID VARCHAR2(10) NOT NULL, /* 고객ID */
	SQNO INTEGER NOT NULL, /* 일련번호 */
	SET_TM TIMESTAMP DEFAULT '00010101 000000.000000' NOT NULL, /* 설정시간 */
	JOB_CD VARCHAR2(255) DEFAULT ' ' NOT NULL, /* 작업코드 */
	CHK_YN CHAR(1) DEFAULT 'N', /* 확인여부 */
	LST_CHK_TS TIMESTAMP DEFAULT '00010101 000000.000000', /* 최종확인일시 */
	WK_ITV_RULE VARCHAR2(7) DEFAULT '1111100', /* 주간규칙 */
	ST_MTH CHAR(2) DEFAULT '01', /* 시작월 */
	ED_MTH CHAR(2) DEFAULT '12', /* 종료월 */
	DEL_YN CHAR(1) DEFAULT 'N', /* 삭제여부 */
	FST_PC_TS TIMESTAMP DEFAULT SYSTIMESTAMP, /* 최초처리일시 */
	PC_TS TIMESTAMP DEFAULT SYSTIMESTAMP, /* 처리일시 */
	LUPD_CNT INTEGER DEFAULT 0 /* 최종수정수 */
);

COMMENT ON TABLE alarm.TS001_JOB_SCH IS '일정';

COMMENT ON COLUMN alarm.TS001_JOB_SCH.DEVER_ID IS '개발자ID';

COMMENT ON COLUMN alarm.TS001_JOB_SCH.CUST_ID IS '고객ID';

COMMENT ON COLUMN alarm.TS001_JOB_SCH.SQNO IS '일련번호';

COMMENT ON COLUMN alarm.TS001_JOB_SCH.SET_TM IS '설정시간';

COMMENT ON COLUMN alarm.TS001_JOB_SCH.JOB_CD IS '작업코드';

COMMENT ON COLUMN alarm.TS001_JOB_SCH.CHK_YN IS '확인여부';

COMMENT ON COLUMN alarm.TS001_JOB_SCH.LST_CHK_TS IS '최종확인일시';

COMMENT ON COLUMN alarm.TS001_JOB_SCH.WK_ITV_RULE IS '주간규칙';

COMMENT ON COLUMN alarm.TS001_JOB_SCH.ST_MTH IS '시작월';

COMMENT ON COLUMN alarm.TS001_JOB_SCH.ED_MTH IS '종료월';

COMMENT ON COLUMN alarm.TS001_JOB_SCH.DEL_YN IS '삭제여부';

COMMENT ON COLUMN alarm.TS001_JOB_SCH.FST_PC_TS IS '최초처리일시';

COMMENT ON COLUMN alarm.TS001_JOB_SCH.PC_TS IS '처리일시';

COMMENT ON COLUMN alarm.TS001_JOB_SCH.LUPD_CNT IS '최종수정수';

CREATE UNIQUE INDEX alarm.PK_TS001_JOB_SCH
	ON alarm.TS001_JOB_SCH (
		DEVER_ID ASC,
		CUST_ID ASC,
		SQNO ASC
	);

ALTER TABLE alarm.TS001_JOB_SCH
	ADD
		CONSTRAINT PK_TS001_JOB_SCH
		PRIMARY KEY (
			DEVER_ID,
			CUST_ID,
			SQNO
		);

ALTER TABLE alarm.TS001_JOB_SCH
	ADD
		CONSTRAINT FK_TU001_USER_I_TO_TS001_JOB_SCH
		FOREIGN KEY (
			DEVER_ID
		)
		REFERENCES alarm.TU001_USER_I (
			DEVER_ID
		);